version: "3.7"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/vhost:/etc/nginx/vhost.d
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_GENERATION=false

  nginx-proxy-acme:
    container_name: nginx-acme
    image: nginxproxy/acme-companion
    volumes:
      - ./nginx/acme:/etc/acme.sh
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=marcinlagowski92@gmail.com

  api:
    container_name: api
    image: ghcr.io/emlagowski/newoncequiz-server:0.11
    environment:
      VIRTUAL_HOST: api.newoncequiz.pl
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: api.newoncequiz.pl

  web:
    container_name: web
    image: ghcr.io/emlagowski/newoncequiz:v0.8
    environment:
      NODE_ENV: PROD
      VIRTUAL_HOST: newoncequiz.pl,www.newoncequiz.pl
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: newoncequiz.pl,www.newoncequiz.pl
