version: "3.7"

services:
  api:
    image: ghcr.io/emlagowski/newoncequiz-server:0.18
    environment:
      VIRTUAL_HOST: ${API_DOMAINS:-api.newoncequiz.pl}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${API_DOMAINS:-api.newoncequiz.pl}
    networks:
      - reverse_proxy

  web:
    image: ghcr.io/emlagowski/newoncequiz:v0.13
    environment:
      NODE_ENV: PROD
      VIRTUAL_HOST: ${WEB_DOMAINS:-newoncequiz.pl,www.newoncequiz.pl}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${WEB_DOMAINS:-newoncequiz.pl,www.newoncequiz.pl}
    networks:
      - reverse_proxy

networks:
  reverse_proxy:
    name: reverse_proxy